# Generated by Django 5.2.13 on 2026-04-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_schema_models_txt'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['org'], name='service_org_idx'),
        ),
    ]
