# Generated by Django 5.2.13 on 2026-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_org_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code for default billing amounts (e.g. USD, KES).', max_length=3),
        ),
    ]
