# Generated by Django 5.2.13 on 2026-04-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0002_initial'),
        ('tenant', '0002_schema_models_txt'),
        ('unit', '0002_schema_models_txt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='billing_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='lease',
            name='billing_same_as_tenant_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='external_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='lease',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Schema: managed_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit'], name='lease_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant'], name='lease_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['managed_by'], name='lease_managed_by_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'end_date'], name='lease_status_end_idx'),
        ),
    ]
