# Generated by Django 5.2.13 on 2026-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='rent_currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code (e.g. USD, KES).', max_length=3),
        ),
    ]
