# Generated by Django 5.2.13 on 2026-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0004_rent_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='deposit_currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code for deposit; may match rent_currency.', max_length=3),
        ),
    ]
