# Generated by Django 5.2.13 on 2026-04-14 21:39

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_active_leases_per_unit(apps, schema_editor):
    Lease = apps.get_model('lease', 'Lease')
    dup_unit_ids = (
        Lease.objects.filter(status='active')
        .values('unit_id')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('unit_id', flat=True)
    )
    for unit_id in dup_unit_ids:
        qs = Lease.objects.filter(unit_id=unit_id, status='active').order_by('id')
        keep = qs.first()
        if keep is None:
            continue
        qs.exclude(pk=keep.pk).update(status='terminated')


def sync_unit_status_from_leases(apps, schema_editor):
    Unit = apps.get_model('unit', 'Unit')
    Lease = apps.get_model('lease', 'Lease')
    for unit in Unit.objects.all().only('id', 'status'):
        has_active = Lease.objects.filter(unit_id=unit.pk, status='active').exists()
        if has_active:
            if unit.status != 'occupied':
                unit.status = 'occupied'
                unit.save(update_fields=['status'])
        elif unit.status != 'maintenance':
            if unit.status != 'vacant':
                unit.status = 'vacant'
                unit.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_deposit_currency'),
        ('tenant', '0002_schema_models_txt'),
        ('unit', '0002_schema_models_txt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(dedupe_active_leases_per_unit, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'active')),
                fields=('unit',),
                name='uniq_active_lease_per_unit',
            ),
        ),
        migrations.RunPython(sync_unit_status_from_leases, migrations.RunPython.noop),
    ]
