# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('landlord', '0002_schema_models_txt'),
        ('org', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='address_line1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='building',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='location_notes',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(default='residential', help_text='Schema column type: residential, commercial, mixed, …', max_length=32),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['org'], name='building_org_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['landlord'], name='building_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['country_code', 'city'], name='building_country_city_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city'], name='building_city_idx'),
        ),
    ]
