# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_schema_models_txt'),
        ('payment', '0002_schema_models_txt'),
        ('payment_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment'], name='payalloc_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='payalloc_invoice_idx'),
        ),
    ]
