# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='org',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='org',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='org',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='org',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='org',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='org',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='org',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='org',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='website',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='org',
            name='org_type',
            field=models.CharField(default='property_manager', help_text='Maps to type in schema: property_manager, owner_group, reit, …', max_length=32),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['org_type'], name='org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['country_code', 'city'], name='org_country_city_idx'),
        ),
    ]
