# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_schema_models_txt'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='tenant',
            name='kyc_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['org'], name='tenant_org_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['org', 'name'], name='tenant_org_name_idx'),
        ),
    ]
