# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_schema_models_txt'),
        ('invoice_line_item', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice'], name='invline_invoice_idx'),
        ),
    ]
