# Generated by Django 5.2.13 on 2026-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_line_item', '0004_invoicelineitem_job_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='line_kind',
            field=models.CharField(blank=True, default='', help_text='rent | service | other | job_recharge; legacy rows may be blank.', max_length=16),
        ),
    ]
