export type OrgDto = {
  id: number;
  name: string;
  org_type: string;
  legal_name: string;
  business_registration_number: string;
  tax_id: string;
  email: string;
  phone: string;
  website: string;
  logo_url: string;
  tagline: string;
  timezone: string;
  language: string;
  locale: string;
  default_currency: "KES" | "UGX" | "TZS" | "USD";
  address_line1: string;
  address_line2: string;
  city: string;
  region: string;
  postal_code: string;
  country_code: string;
  created_at: string;
  updated_at: string;
};
