# Generated by Django 5.2.13 on 2026-04-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_note', '0002_initial'),
        ('invoice', '0003_schema_models_txt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Schema: created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['invoice'], name='creditnote_invoice_idx'),
        ),
    ]
