# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_schema_models_txt'),
        ('service', '0001_initial'),
        ('service_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesubscription',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['lease'], name='svcsub_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['service'], name='svcsub_service_idx'),
        ),
    ]
