# Generated by Django 5.2.13 on 2026-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_subscription', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubscription',
            name='currency',
            field=models.CharField(blank=True, help_text='ISO 4217 code for this rate; defaults from service if blank.', max_length=3),
        ),
    ]
