# Generated by Django 5.2.13 on 2026-04-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='org.org')),
            ],
            options={
                'db_table': 'expense_category',
                'indexes': [models.Index(fields=['org'], name='exp_cat_org_idx'), models.Index(fields=['org', 'is_active'], name='exp_cat_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('org', 'name'), name='uniq_expense_category_name_per_org'), models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('org', 'code'), name='uniq_expense_category_code_per_org')],
            },
        ),
    ]
