# Generated by Django 5.2.13 on 2026-04-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('org', '0002_schema_models_txt'),
        ('tenant', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16)),
                ('cycle_year', models.PositiveSmallIntegerField()),
                ('cycle_month', models.PositiveSmallIntegerField(blank=True, help_text='1-12 for monthly cycles; null for yearly cycles.', null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('paid', 'Paid'), ('void', 'Void')], default='upcoming', max_length=16)),
                ('units_count', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('amount_due', models.DecimalField(decimal_places=2, default='0.00', max_digits=14)),
                ('credit_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_payments', to='org.org')),
                ('tenant', models.ForeignKey(blank=True, help_text='Optional billing contact tenant record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_payments', to='tenant.tenant')),
            ],
            options={
                'db_table': 'license_payment',
            },
        ),
        migrations.AddIndex(
            model_name='licensepayment',
            index=models.Index(fields=['org', 'status'], name='licpay_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='licensepayment',
            index=models.Index(fields=['org', 'mode', 'cycle_year'], name='licpay_org_mode_year_idx'),
        ),
        migrations.AddIndex(
            model_name='licensepayment',
            index=models.Index(fields=['period_start', 'period_end'], name='licpay_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='licensepayment',
            constraint=models.UniqueConstraint(fields=('org', 'mode', 'cycle_year', 'cycle_month'), name='uniq_license_cycle_per_org'),
        ),
    ]
