# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


def _ensure_default_roles(apps, org_id):
    RoleDefinition = apps.get_model('access', 'RoleDefinition')
    RoleDefinition.objects.get_or_create(
        org_id=org_id,
        key='admin',
        defaults={'name': 'Administrator', 'is_system': True},
    )
    RoleDefinition.objects.get_or_create(
        org_id=org_id,
        key='org_member',
        defaults={'name': 'Organization member', 'is_system': True},
    )


def _role_key_for_legacy(role: str) -> str:
    return {
        'org_admin': 'admin',
        'property_manager': 'org_member',
        'read_only': 'org_member',
    }.get(role, role)


def forwards_user_role_roles(apps, schema_editor):
    UserRole = apps.get_model('user_role', 'UserRole')
    RoleDefinition = apps.get_model('access', 'RoleDefinition')
    for ur in UserRole.objects.all():
        _ensure_default_roles(apps, ur.org_id)
        key = _role_key_for_legacy(ur.role)
        rd, _ = RoleDefinition.objects.get_or_create(
            org_id=ur.org_id,
            key=key,
            defaults={'name': key.replace('_', ' ').title(), 'is_system': False},
        )
        ur.role_definition_id = rd.pk
        ur.save(update_fields=['role_definition_id'])


def backwards_user_role_roles(apps, schema_editor):
    UserRole = apps.get_model('user_role', 'UserRole')
    for ur in UserRole.objects.select_related('role_definition'):
        ur.role = ur.role_definition.key
        ur.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('user_role', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='role_definition',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='user_roles',
                to='access.roledefinition',
            ),
        ),
        migrations.RunPython(forwards_user_role_roles, backwards_user_role_roles),
        migrations.RemoveField(model_name='userrole', name='role'),
        migrations.AlterField(
            model_name='userrole',
            name='role_definition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='user_roles',
                to='access.roledefinition',
            ),
        ),
    ]
