# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('org', '0002_schema_models_txt'),
        ('user_role', '0003_userrole_role_definition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.CharField(blank=True, help_text='Denormalized role key (schema user_role.role); synced from role_definition.key.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['org'], name='user_role_org_idx'),
        ),
    ]
