# Generated by Django 5.2.13 on 2026-04-22 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('invoice', '0004_invoice_issue_kind'),
        ('unit', '0003_unit_payment_code_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_link', to='unit.unit')),
            ],
            options={
                'db_table': 'payment_link',
            },
        ),
        migrations.CreateModel(
            name='PaymentLinkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=16)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_email', models.EmailField(blank=True, max_length=320)),
                ('payer_phone', models.CharField(blank=True, max_length=64)),
                ('payment_method', models.CharField(default='card', max_length=32)),
                ('provider_ref', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_link_payments', to='invoice.invoice')),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='payment_link.paymentlink')),
            ],
            options={
                'db_table': 'payment_link_payment',
            },
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['is_active'], name='paylink_active_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlink',
            index=models.Index(fields=['expires_at'], name='paylink_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkpayment',
            index=models.Index(fields=['payment_link', 'status'], name='plinkpay_link_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkpayment',
            index=models.Index(fields=['invoice'], name='plinkpay_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlinkpayment',
            index=models.Index(fields=['provider_ref'], name='plinkpay_provider_idx'),
        ),
    ]
