# Generated by Django 5.2.13 on 2026-04-22 19:00

from django.db import migrations


def backfill_payment_link_slugs(apps, schema_editor):
    PaymentLink = apps.get_model('payment_link', 'PaymentLink')
    for link in PaymentLink.objects.select_related('unit').all():
        unit = link.unit
        if not unit or not unit.payment_code:
            continue
        if link.slug == unit.payment_code:
            continue
        if link.slug.startswith('UNIT-'):
            conflict = PaymentLink.objects.filter(slug=unit.payment_code).exclude(pk=link.pk).exists()
            if not conflict:
                link.slug = unit.payment_code
                link.save(update_fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('payment_link', '0001_initial'),
        ('unit', '0004_backfill_payment_codes'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_link_slugs, migrations.RunPython.noop),
    ]
