# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0003_schema_models_txt'),
        ('org', '0002_schema_models_txt'),
        ('payment', '0001_initial'),
        ('tenant', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['org', 'payment_date'], name='payment_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='payment_tenant_date_idx'),
        ),
    ]
