# Generated by Django 5.2.13 on 2026-04-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0002_initial'),
        ('job_order', '0001_initial'),
        ('lease', '0003_schema_models_txt'),
        ('org', '0002_schema_models_txt'),
        ('unit', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='job_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='job_order.joborder'),
        ),
        migrations.AddField(
            model_name='expense',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='lease.lease'),
        ),
        migrations.AddField(
            model_name='expense',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='org.org'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='unit.unit'),
        ),
    ]
