# Generated by Django 5.2.13 on 2026-04-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0003_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['org', 'expense_date'], name='expense_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_category'], name='expense_category_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vendor'], name='expense_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['building'], name='expense_building_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['lease'], name='expense_lease_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['job_order'], name='expense_job_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('expense_number__gt', '')), fields=('org', 'expense_number'), name='uniq_expense_number_per_org'),
        ),
    ]
