# Generated by Django 5.2.13 on 2026-04-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_order', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='vendor.vendor'),
        ),
        migrations.AddIndex(
            model_name='joborder',
            index=models.Index(fields=['org', 'status'], name='job_order_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='joborder',
            index=models.Index(fields=['building'], name='job_order_building_idx'),
        ),
        migrations.AddIndex(
            model_name='joborder',
            index=models.Index(fields=['unit'], name='job_order_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='joborder',
            index=models.Index(fields=['vendor'], name='job_order_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='joborder',
            index=models.Index(fields=['scheduled_start'], name='job_order_scheduled_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='joborder',
            constraint=models.UniqueConstraint(fields=('org', 'job_number'), name='uniq_job_number_per_org'),
        ),
    ]
