# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_initial'),
        ('lease', '0003_schema_models_txt'),
        ('org', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_region',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to_tax_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'status'], name='invoice_lease_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['lease', 'due_date'], name='invoice_lease_due_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['org', 'issue_date'], name='invoice_org_issue_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__gt', '')), fields=('org', 'invoice_number'), name='uniq_invoice_number_per_org'),
        ),
    ]
