# Generated by Django 5.2.13 on 2026-04-13 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=64)),
                ('unit_type', models.CharField(default='apartment', max_length=32)),
                ('status', models.CharField(default='vacant', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='building.building')),
            ],
            options={
                'db_table': 'unit',
                'constraints': [models.UniqueConstraint(fields=('building', 'unit_number'), name='uniq_unit_number_per_building')],
            },
        ),
    ]
