# Generated by Django 5.2.13 on 2026-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_schema_models_txt'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='address_override_city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='unit',
            name='address_override_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='unit',
            name='entrance',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='unit',
            name='internal_notes',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default='apartment', help_text='Schema column type: apartment, shop, office, …', max_length=32),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building'], name='unit_building_idx'),
        ),
    ]
