# Generated by Django 5.2.13 on 2026-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('unit', '0002_schema_models_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='payment_code',
            field=models.CharField(
                blank=True,
                help_text='Stable public code for tenant-facing payment links.',
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='unit',
            name='payment_code_status',
            field=models.CharField(
                choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')],
                default='active',
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['payment_code_status'], name='unit_paycode_status_idx'),
        ),
    ]
