# Generated by Django 5.2.13 on 2026-04-22 19:00

import hashlib

from django.db import migrations


def _hash_code(unit_id: int, building_id: int, unit_number: str, salt: int = 0) -> str:
    seed = f'{building_id}:{unit_number}:{unit_id}:{salt}'
    return hashlib.sha256(seed.encode('utf-8')).hexdigest()[:8]


def backfill_payment_codes(apps, schema_editor):
    Unit = apps.get_model('unit', 'Unit')
    used_codes = set(Unit.objects.exclude(payment_code__isnull=True).exclude(payment_code='').values_list('payment_code', flat=True))
    for unit in Unit.objects.filter(payment_code__isnull=True) | Unit.objects.filter(payment_code=''):
        salt = 0
        while True:
            candidate = _hash_code(unit.id, unit.building_id, unit.unit_number or '', salt=salt)
            if candidate not in used_codes:
                unit.payment_code = candidate
                unit.save(update_fields=['payment_code'])
                used_codes.add(candidate)
                break
            salt += 1


class Migration(migrations.Migration):
    dependencies = [
        ('unit', '0003_unit_payment_code_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_payment_codes, migrations.RunPython.noop),
    ]
