"""Role keys, scopes, and permission levels for access control."""

ROLE_ADMIN = 'admin'
ROLE_ORG_MEMBER = 'org_member'

SCOPE_ORG = 'ORG'
SCOPE_BUILDING = 'BUILDING'
SCOPE_UNIT = 'UNIT'
SCOPE_LEASE = 'LEASE'
SCOPE_TENANT = 'TENANT'

PERM_VIEW = 'VIEW'
PERM_MANAGE = 'MANAGE'

ALL_SCOPES = (SCOPE_ORG, SCOPE_BUILDING, SCOPE_UNIT, SCOPE_LEASE, SCOPE_TENANT)
ALL_PERMS = (PERM_VIEW, PERM_MANAGE)
